name: Build Han-3+ Character Dictionary

on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - ".github/workflows/build-han-3plus.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_REPO: Kimeiga/japanese-dict-han-3plus

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Download dictionary source files
        run: |
          # Create directories if they don't exist
          mkdir -p dictionaries/jmdict/source
          mkdir -p dictionaries/jmnedict/source

          # Download JMdict file with examples
          echo "Downloading JMdict file with examples..."
          curl -L -o dictionaries/jmdict/source/jmdict-examples-eng-3.6.1.json.zip https://github.com/scriptin/jmdict-simplified/releases/download/3.6.1+20250505122413/jmdict-examples-eng-3.6.1+20250505122413.json.zip

          # Unzip the JMdict file
          echo "Unzipping JMdict file..."
          unzip -o dictionaries/jmdict/source/jmdict-examples-eng-3.6.1.json.zip -d dictionaries/jmdict/source/

          # Download JMNedict file
          echo "Downloading JMNedict file..."
          curl -L -o dictionaries/jmnedict/source/jmnedict-all-3.6.1.json.zip https://github.com/scriptin/jmdict-simplified/releases/download/3.6.1+20250505122413/jmnedict-all-3.6.1+20250505122413.json.zip

          # Unzip the JMNedict file
          echo "Unzipping JMNedict file..."
          unzip -o dictionaries/jmnedict/source/jmnedict-all-3.6.1.json.zip -d dictionaries/jmnedict/source/

          # Verify files were downloaded
          ls -la dictionaries/jmdict/source/
          ls -la dictionaries/jmnedict/source/
          ls -la dictionaries/kanjidic/source/
          ls -la dictionaries/chinese_chars/source/
          ls -la dictionaries/chinese_words/source/

      - name: Generate Han 3+ character dictionary files
        run: |
          # The new sharded processor generates all shards at once, but we only need the han-3plus shard
          go run cmd/kiokun/main.go --writers 16 --silent
          echo "Generated $(find output_han_3plus -type f | wc -l) files"

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Push to output repository
        run: |
          # Navigate to output directory
          cd output_han_3plus

          # Initialize new git repo (removing any existing one)
          rm -rf .git
          git init

          # Add the remote
          git remote add origin https://x-access-token:${{ secrets.DICTIONARY_DEPLOY_TOKEN }}@github.com/${{ env.OUTPUT_REPO }}.git

          # Add all files
          git add .

          # Create commit
          git commit -m "Update Han 3+ character dictionary files"

          # Force push to completely replace contents
          git push -f origin master:main
