name: Build Non-Han Dictionary

on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - ".github/workflows/build-non-han.yml"
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_REPO: your-username/japanese-dict-non-han

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Download dictionary source files
        run: |
          # Add commands to download your source files
          # For example:
          # curl -L -o dictionaries/jmdict/source/jmdict-examples-eng-3.6.1.json https://example.com/path/to/jmdict.json

      - name: Generate Non-Han dictionary files
        run: |
          go run cmd/kiokun/main.go --writers 16 --mode=non-han --silent
          echo "Generated $(find output_non_han -type f | wc -l) files"

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Push to output repository
        run: |
          # Navigate to output directory
          cd output_non_han

          # Initialize new git repo (removing any existing one)
          rm -rf .git
          git init

          # Add the remote
          git remote add origin https://x-access-token:${{ secrets.DICTIONARY_DEPLOY_TOKEN }}@github.com/${{ env.OUTPUT_REPO }}.git

          # Add all files
          git add .

          # Create commit
          git commit -m "Update Non-Han dictionary files"

          # Force push to completely replace contents
          git push -f origin master:main
