name: Build Dictionary

on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - "dictionaries/**"
      - "processor/**"
      - ".github/workflows/dictionary-build.yml"
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 0 1 * *" # Run monthly

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this to grant write permissions
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Download dictionary source files
        run: |
          # Create directories if they don't exist
          mkdir -p dictionaries/jmdict/source
          mkdir -p dictionaries/jmnedict/source

          # Download JMdict file
          echo "Downloading JMdict file..."
          curl -L -o dictionaries/jmdict/source/jmdict-examples-eng-3.6.1.json https://github.com/scriptin/jmdict-simplified/releases/download/3.6.1/jmdict-eng-3.6.1.json

          # Download JMNedict file
          echo "Downloading JMNedict file..."
          curl -L -o dictionaries/jmnedict/source/jmnedict-all-3.6.1.json https://github.com/scriptin/jmnedict-simplified/releases/download/3.6.1/jmnedict-3.6.1.json

          # Verify files were downloaded
          ls -la dictionaries/jmdict/source/
          ls -la dictionaries/jmnedict/source/
          ls -la dictionaries/kanjidic/source/
          ls -la dictionaries/chinese_chars/source/
          ls -la dictionaries/chinese_words/source/

      - name: Build Dictionary
        run: |
          go run cmd/kiokun/main.go --writers 16 --silent
          echo "Generated $(find output -type f | wc -l) files"

      - name: Commit dictionary files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f output/
          git commit -m "Update dictionary files" || echo "No changes to commit"
          git push
